/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/": {
    /**
     * Get a list of users
     * @description Retrieve a list of user entities.
     */
    get: {
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": components["schemas"]["User"][];
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": external["openapi.specification.json"];
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    User: {
      /** @default johndoe@gmail.com */
      email?: string;
      /** @default securePassword123 */
      password?: string;
      rememberMe?: boolean;
      /** @default john */
      firstName?: string;
      /** @default Doe */
      lastName?: string;
      tcAgreed?: boolean;
      /** @default false */
      firstSignOn?: boolean;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
    };
    Error: {
      message?: string;
    };
    error: {
      /** @default 123 */
      status?: number;
      /** @default Something went wrong */
      message?: string;
      error?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export interface external {
  "openapi.specification.json": unknown;
}

export type operations = Record<string, never>;
